# Generated by Django 3.1.4 on 2021-06-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, help_text='创建日期', verbose_name='创建日期')),
                ('update_at', models.DateTimeField(auto_now=True, help_text='更新日期', verbose_name='最后修改')),
                ('name', models.CharField(max_length=64, verbose_name='配置项')),
                ('key', models.CharField(max_length=32, unique=True, verbose_name='配置键')),
                ('value', models.JSONField(max_length=40280, null=True, verbose_name='配置值')),
                ('enable', models.BooleanField(default=False, verbose_name='启用')),
                ('module_name', models.CharField(default='默认模块', max_length=64, verbose_name='所属模块')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
            },
        ),
    ]
